-- Схема eplus_work для PostgreSQL.
-- Запускать в pgAdmin / psql, подключившись к базе: eplus_work
--
-- psql -U es_api -d eplus_work -f 002_eplus_work_schema.sql
--
-- Важно:
-- - Это канонический набор ES_* таблиц, который уже использует сервис при синхронизации.
-- - Если в живой MSSQL eplus_work есть дополнительные ES_* таблицы
--   (например, ES_FIRMA / ES_MNN / ES_PHGROUP), сгенерируй для них DDL через
--   mssql_export_schema_for_pg.sql и выполни перед запуском UniversalSync.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "ES_ATC" (
    "ID_ATC" UUID NOT NULL PRIMARY KEY,
    "C_PARENT_ATC" UUID,
    "ATC_CODE" TEXT,
    "ATC_NAME" TEXT,
    "ID_ES_ATC" BIGINT NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "TS" BYTEA NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_COUNTRY" (
    "COUNTRY_NAME" TEXT,
    "COD_OKSM" TEXT,
    "K_ALFA3" TEXT,
    "KOD_COUNTRY" BIGINT NOT NULL,
    "GUID_COUNTRY" UUID NOT NULL PRIMARY KEY,
    "NAME_SHORT" TEXT,
    "DELETED" TIMESTAMPTZ,
    "TS" BYTEA NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_EF2" (
    "GUID_ES" UUID NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "BARCODE" TEXT,
    "CUREFORM_COD" TEXT,
    "CUREFORM_NAME" TEXT,
    "INN_NAME_RUS" TEXT,
    "INN_NAME_LAT" TEXT,
    "PRODUCER_COD" BIGINT,
    "TRN_NAME_RUS" TEXT,
    "TRN_NAME_LAT" TEXT,
    "UPAK_COD" BIGINT,
    "DATA_AN" TIMESTAMPTZ,
    "DATA_REG" TIMESTAMPTZ,
    "DOSAGE" TEXT,
    "PR_JNVLS" BOOLEAN,
    "PR_LGOTA" BOOLEAN,
    "PR_NOT_RECEPT" BOOLEAN,
    "PR_OA" BOOLEAN,
    "PR_BAD" BOOLEAN,
    "SPISOK_AB" TEXT,
    "PR_PKKN" BOOLEAN,
    "N_PKKN" INTEGER,
    "N_FV" BIGINT,
    "UPAK_1" TEXT,
    "UPAK_2" TEXT,
    "UPAK_3" TEXT,
    "KOL_1_UPAK" BIGINT,
    "KOL_CUREFORM" BIGINT,
    "KOL_VES" NUMERIC(19,4),
    "KOL_VES_UNIT" TEXT,
    "SROK_SAVED" TEXT,
    "STORING_CONDITION" TEXT,
    "KOMPLEKTN" TEXT,
    "N_LICENSE" TEXT,
    "N_REG_UDOST" TEXT,
    "REGISTRATOR_COD" BIGINT,
    "REGISTR_STATUS" TEXT,
    "REESTR_PRICE" NUMERIC(19,4),
    "KOD_ES" BIGINT NOT NULL,
    "NDS_RATE" NUMERIC(19,4) NOT NULL,
    "GUID_ES_CHAR" TEXT,
    "ID_ES" BIGINT NOT NULL,
    "C_INSTRUCTION" UUID,
    "DISCRIBE" TEXT,
    "RATING" INTEGER NOT NULL,
    "UPDATED" TIMESTAMPTZ NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "PACK_VOLUME" NUMERIC(19,4),
    "PACK_WEIGHT" NUMERIC(18,2),
    "BOX_PACK_QUANTITY" INTEGER,
    "IMMUNOBIOLOGICAL" BOOLEAN,
    "TS" BYTEA NOT NULL,
    "GUID_PKU_LIST" UUID,
    "IS_ALCOHOL_CONTENT" BOOLEAN,
    "IS_KIZ" BOOLEAN,
    "GUID_GOODS_CLASSIFIER" UUID,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_ATC" (
    "GUID_ES" UUID NOT NULL,
    "ID_ATC" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "ID_ATC")
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_FG" (
    "GUID_ES" UUID NOT NULL,
    "C_FG" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "C_FG")
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_GOODS" (
    "GUID_ES" UUID NOT NULL,
    "ID_GOODS_GLOBAL" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "ID_GOODS_GLOBAL")
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_GROUP" (
    "GUID_ES" UUID NOT NULL,
    "ID_GROUP" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "ID_GROUP")
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_STORE_CONDITION" (
    "GUID_ES" UUID NOT NULL,
    "ID_STORE_CONDITION_GLOBAL" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "ID_STORE_CONDITION_GLOBAL")
);

CREATE TABLE IF NOT EXISTS "ES_FARMGROUP" (
    "ID_FARMGROUP" UUID NOT NULL PRIMARY KEY,
    "C_PARENT_GROUP" UUID,
    "FARMGROUP_NAME" TEXT,
    "FARMGROUP_DISCRIBE" TEXT,
    "ID_ES_FARMGROUP" BIGINT NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_GOODS_CLASSIFIER" (
    "ID_GOODS_CLASSIFIER" BIGINT NOT NULL,
    "GUID_GOODS_CLASSIFIER" UUID NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "INSERTED" TIMESTAMPTZ NOT NULL,
    "UPDATED" TIMESTAMPTZ NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_GROUP" (
    "ID_GROUP" UUID NOT NULL PRIMARY KEY,
    "C_PARENT_GROUP" UUID,
    "GROUP_NAME" TEXT,
    "ID_ES_GROUP" BIGINT NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_INSTRUCTION" (
    "ID_INSTRUCTION" BIGINT NOT NULL,
    "GUID_INSTRUCTION" UUID NOT NULL PRIMARY KEY,
    "INSTRUCTION" TEXT NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "COMPOSITION" TEXT,
    "INDICATION" TEXT,
    "DOSAGE" TEXT,
    "LACTATION" TEXT,
    "PHARM_ACTION" TEXT,
    "CONTRA_INDICATION" TEXT,
    "SIDE_EFFECT" TEXT,
    "INTERACTION" TEXT,
    "OVER_DOSAGE" TEXT,
    "SPECIAL_INSTRUCTION" TEXT,
    "GOODS_DESC" TEXT,
    "STORING_CONDITION" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_PKU_LIST" (
    "ID_PKU_LIST" BIGINT NOT NULL,
    "GUID_PKU_LIST" UUID NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "DATE_MODIFIED" TIMESTAMPTZ,
    "DATE_DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_PRODUCER" (
    "COUNTRY_COD" BIGINT,
    "PRODUCER_NAME" TEXT,
    "KOD_PRODUCER" BIGINT NOT NULL,
    "GUID_PRODUCER" UUID NOT NULL PRIMARY KEY,
    "DELETED" TIMESTAMPTZ,
    "TS" BYTEA NOT NULL,
    "DATE_MODIFIED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_STORE_CONDITION" (
    "ID_STORE_CONDITION_GLOBAL" UUID NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "INSERTED" TIMESTAMPTZ NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_SUPPLIER" (
    "ID_ES_SUPPLIER" BIGINT NOT NULL,
    "GUID_ES_SUPPLIER" UUID NOT NULL PRIMARY KEY,
    "C_CONTRACTOR" UUID,
    "NAME" TEXT,
    "TOWN" TEXT,
    "PHONE" TEXT,
    "ADDRESS" TEXT,
    "EMAIL" TEXT,
    "DELETED" TIMESTAMPTZ,
    "REGION_NAME" TEXT,
    "REGION_CODE" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

-- Быстрая проверка: что набор ES_* уже создан
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name ILIKE 'es_%'
ORDER BY table_name;
