-- Схема elfisa для PostgreSQL (из выгрузки MSSQL).
-- Запускать в pgAdmin / psql, подключившись к базе: elfisa
--
-- psql -U es_api -d elfisa -f 002_elfisa_schema.sql

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS "AuditLog" (
    "LogID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID" TEXT,
    "Username" TEXT,
    "LogLevel" TEXT NOT NULL,
    "Category" TEXT,
    "Action" TEXT,
    "Message" TEXT NOT NULL,
    "Details" TEXT,
    "IPAddress" TEXT,
    "UserAgent" TEXT,
    "RequestMethod" TEXT,
    "RequestPath" TEXT,
    "ResponseStatus" INTEGER,
    "ExecutionTimeMs" INTEGER,
    "ErrorMessage" TEXT,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "Buyer" (
    "BuyerID" UUID NOT NULL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "INN" TEXT,
    "RegionID" UUID,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "Code" TEXT,
    "Phone" TEXT,
    "Address" TEXT,
    "Email" TEXT
);

CREATE TABLE IF NOT EXISTS "BuyerApplication" (
    "BuyerApplicationID" UUID NOT NULL PRIMARY KEY,
    "BuyerID" UUID NOT NULL,
    "BuyerUserID" UUID NOT NULL,
    "LastPriceUpdate" TIMESTAMPTZ,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "BuyerLocation" (
    "BuyerLocationID" UUID NOT NULL PRIMARY KEY,
    "BuyerID" UUID NOT NULL,
    "Address" TEXT NOT NULL,
    "RegionID" UUID,
    "IsDefault" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "BuyerPriceList" (
    "BuyerPriceListID" UUID NOT NULL PRIMARY KEY,
    "BuyerID" UUID NOT NULL,
    "PriceListID" UUID NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "MarkupPct" NUMERIC(6,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS "BuyerUser" (
    "BuyerUserID" UUID NOT NULL PRIMARY KEY,
    "BuyerID" UUID NOT NULL,
    "FullName" TEXT NOT NULL,
    "Email" TEXT NOT NULL,
    "Phone" TEXT,
    "Role" TEXT,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "Password" TEXT
);

CREATE TABLE IF NOT EXISTS "DBFFieldMapping" (
    "MappingID" UUID NOT NULL PRIMARY KEY,
    "ImportPointID" UUID NOT NULL,
    "DBFFieldName" TEXT NOT NULL,
    "TargetFieldName" TEXT NOT NULL,
    "DataType" TEXT NOT NULL,
    "IsRequired" BOOLEAN NOT NULL,
    "DefaultValue" TEXT,
    "TransformRule" TEXT,
    "DisplayOrder" INTEGER NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_ATC" (
    "ID_ATC" UUID NOT NULL PRIMARY KEY,
    "C_PARENT_ATC" UUID,
    "ATC_CODE" TEXT,
    "ATC_NAME" TEXT,
    "ID_ES_ATC" BIGINT NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "TS" BYTEA NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_COUNTRY" (
    "COUNTRY_NAME" TEXT,
    "COD_OKSM" TEXT,
    "K_ALFA3" TEXT,
    "KOD_COUNTRY" BIGINT NOT NULL,
    "GUID_COUNTRY" UUID NOT NULL PRIMARY KEY,
    "NAME_SHORT" TEXT,
    "DELETED" TIMESTAMPTZ,
    "TS" BYTEA NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_EF2" (
    "GUID_ES" UUID NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "BARCODE" TEXT,
    "CUREFORM_COD" TEXT,
    "CUREFORM_NAME" TEXT,
    "INN_NAME_RUS" TEXT,
    "INN_NAME_LAT" TEXT,
    "PRODUCER_COD" BIGINT,
    "TRN_NAME_RUS" TEXT,
    "TRN_NAME_LAT" TEXT,
    "UPAK_COD" BIGINT,
    "DATA_AN" TIMESTAMPTZ,
    "DATA_REG" TIMESTAMPTZ,
    "DOSAGE" TEXT,
    "PR_JNVLS" BOOLEAN,
    "PR_LGOTA" BOOLEAN,
    "PR_NOT_RECEPT" BOOLEAN,
    "PR_OA" BOOLEAN,
    "PR_BAD" BOOLEAN,
    "SPISOK_AB" TEXT,
    "PR_PKKN" BOOLEAN,
    "N_PKKN" INTEGER,
    "N_FV" BIGINT,
    "UPAK_1" TEXT,
    "UPAK_2" TEXT,
    "UPAK_3" TEXT,
    "KOL_1_UPAK" BIGINT,
    "KOL_CUREFORM" BIGINT,
    "KOL_VES" NUMERIC(19,4),
    "KOL_VES_UNIT" TEXT,
    "SROK_SAVED" TEXT,
    "STORING_CONDITION" TEXT,
    "KOMPLEKTN" TEXT,
    "N_LICENSE" TEXT,
    "N_REG_UDOST" TEXT,
    "REGISTRATOR_COD" BIGINT,
    "REGISTR_STATUS" TEXT,
    "REESTR_PRICE" NUMERIC(19,4),
    "KOD_ES" BIGINT NOT NULL,
    "NDS_RATE" NUMERIC(19,4) NOT NULL,
    "GUID_ES_CHAR" TEXT,
    "ID_ES" BIGINT NOT NULL,
    "C_INSTRUCTION" UUID,
    "DISCRIBE" TEXT,
    "RATING" INTEGER NOT NULL,
    "UPDATED" TIMESTAMPTZ NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "PACK_VOLUME" NUMERIC(19,4),
    "PACK_WEIGHT" NUMERIC(18,2),
    "BOX_PACK_QUANTITY" INTEGER,
    "IMMUNOBIOLOGICAL" BOOLEAN,
    "TS" BYTEA NOT NULL,
    "GUID_PKU_LIST" UUID,
    "IS_ALCOHOL_CONTENT" BOOLEAN,
    "IS_KIZ" BOOLEAN,
    "GUID_GOODS_CLASSIFIER" UUID,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_ATC" (
    "GUID_ES" UUID NOT NULL,
    "ID_ATC" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "ID_ATC")
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_FG" (
    "GUID_ES" UUID NOT NULL,
    "C_FG" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "C_FG")
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_GOODS" (
    "GUID_ES" UUID NOT NULL,
    "ID_GOODS_GLOBAL" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "ID_GOODS_GLOBAL")
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_GROUP" (
    "GUID_ES" UUID NOT NULL,
    "ID_GROUP" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "ID_GROUP")
);

CREATE TABLE IF NOT EXISTS "ES_ES_2_STORE_CONDITION" (
    "GUID_ES" UUID NOT NULL,
    "ID_STORE_CONDITION_GLOBAL" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    PRIMARY KEY ("GUID_ES", "ID_STORE_CONDITION_GLOBAL")
);

CREATE TABLE IF NOT EXISTS "ES_FARMGROUP" (
    "ID_FARMGROUP" UUID NOT NULL PRIMARY KEY,
    "C_PARENT_GROUP" UUID,
    "FARMGROUP_NAME" TEXT,
    "FARMGROUP_DISCRIBE" TEXT,
    "ID_ES_FARMGROUP" BIGINT NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_GOODS_CLASSIFIER" (
    "ID_GOODS_CLASSIFIER" BIGINT NOT NULL,
    "GUID_GOODS_CLASSIFIER" UUID NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "INSERTED" TIMESTAMPTZ NOT NULL,
    "UPDATED" TIMESTAMPTZ NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_GROUP" (
    "ID_GROUP" UUID NOT NULL PRIMARY KEY,
    "C_PARENT_GROUP" UUID,
    "GROUP_NAME" TEXT,
    "ID_ES_GROUP" BIGINT NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_INSTRUCTION" (
    "ID_INSTRUCTION" BIGINT NOT NULL,
    "GUID_INSTRUCTION" UUID NOT NULL PRIMARY KEY,
    "INSTRUCTION" TEXT NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "COMPOSITION" TEXT,
    "INDICATION" TEXT,
    "DOSAGE" TEXT,
    "LACTATION" TEXT,
    "PHARM_ACTION" TEXT,
    "CONTRA_INDICATION" TEXT,
    "SIDE_EFFECT" TEXT,
    "INTERACTION" TEXT,
    "OVER_DOSAGE" TEXT,
    "SPECIAL_INSTRUCTION" TEXT,
    "GOODS_DESC" TEXT,
    "STORING_CONDITION" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_PKU_LIST" (
    "ID_PKU_LIST" BIGINT NOT NULL,
    "GUID_PKU_LIST" UUID NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "DATE_MODIFIED" TIMESTAMPTZ,
    "DATE_DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_PRODUCER" (
    "COUNTRY_COD" BIGINT,
    "PRODUCER_NAME" TEXT,
    "KOD_PRODUCER" BIGINT NOT NULL,
    "GUID_PRODUCER" UUID NOT NULL PRIMARY KEY,
    "DELETED" TIMESTAMPTZ,
    "TS" BYTEA NOT NULL,
    "DATE_MODIFIED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_STORE_CONDITION" (
    "ID_STORE_CONDITION_GLOBAL" UUID NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "INSERTED" TIMESTAMPTZ NOT NULL,
    "DELETED" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ES_SUPPLIER" (
    "ID_ES_SUPPLIER" BIGINT NOT NULL,
    "GUID_ES_SUPPLIER" UUID NOT NULL PRIMARY KEY,
    "C_CONTRACTOR" UUID,
    "NAME" TEXT,
    "TOWN" TEXT,
    "PHONE" TEXT,
    "ADDRESS" TEXT,
    "EMAIL" TEXT,
    "DELETED" TIMESTAMPTZ,
    "REGION_NAME" TEXT,
    "REGION_CODE" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "is_active" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "ImportPoint" (
    "ImportPointID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID,
    "Name" TEXT NOT NULL,
    "Description" TEXT,
    "DBFFilePath" TEXT,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL,
    "SourceFilePath" TEXT,
    "SourceType" TEXT NOT NULL,
    "FtpHost" TEXT,
    "FtpPort" INTEGER,
    "FtpUser" TEXT,
    "FtpPassword" TEXT,
    "FtpRemotePath" TEXT
);

CREATE TABLE IF NOT EXISTS "InvoiceData" (
    "InvoiceDataID" UUID NOT NULL PRIMARY KEY,
    "InvoiceImportID" UUID NOT NULL,
    "SupplierID" UUID NOT NULL,
    "InvoiceNumber" TEXT,
    "InvoiceDate" TIMESTAMPTZ,
    "ItemCode" TEXT,
    "ItemName" TEXT,
    "Quantity" NUMERIC(18,3),
    "Price" NUMERIC(18,2),
    "BatchNumber" TEXT,
    "ExpiryDate" TIMESTAMPTZ,
    "Barcode" TEXT,
    "RawData" TEXT,
    "IsProcessed" BOOLEAN NOT NULL,
    "ProcessedAt" TIMESTAMPTZ,
    "ErrorMessage" TEXT,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "Series" TEXT,
    "Manufacturer" TEXT,
    "Country" TEXT
);

CREATE TABLE IF NOT EXISTS "InvoiceImport" (
    "InvoiceImportID" UUID NOT NULL PRIMARY KEY,
    "ImportPointID" UUID NOT NULL,
    "FileName" TEXT NOT NULL,
    "FilePath" TEXT NOT NULL,
    "FileSize" BIGINT,
    "RecordsTotal" INTEGER NOT NULL,
    "RecordsProcessed" INTEGER NOT NULL,
    "RecordsSkipped" INTEGER NOT NULL,
    "RecordsError" INTEGER NOT NULL,
    "ImportStatus" TEXT NOT NULL,
    "ErrorMessage" TEXT,
    "StartedAt" TIMESTAMPTZ,
    "CompletedAt" TIMESTAMPTZ,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "CreatedBy" TEXT
);

CREATE TABLE IF NOT EXISTS "ItemHistory" (
    "ItemHistoryID" UUID NOT NULL PRIMARY KEY,
    "SupplierPriceID" UUID NOT NULL,
    "GUID_ES" UUID,
    "OldItemCode" TEXT,
    "NewItemCode" TEXT,
    "OldItemName" TEXT,
    "NewItemName" TEXT,
    "OldSupplierItemName" TEXT,
    "NewSupplierItemName" TEXT,
    "OldBarcode" TEXT,
    "NewBarcode" TEXT,
    "OldMatchMethod" TEXT,
    "NewMatchMethod" TEXT,
    "OldMatchConfidence" NUMERIC(5,2),
    "NewMatchConfidence" NUMERIC(5,2),
    "OldIsConfirmed" BOOLEAN,
    "NewIsConfirmed" BOOLEAN,
    "ChangedAt" TIMESTAMPTZ NOT NULL,
    "ChangedByInvoiceImportID" UUID,
    "ChangeType" TEXT,
    "Reason" TEXT
);

CREATE TABLE IF NOT EXISTS "MapStatus" (
    "MapStatusID" UUID NOT NULL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Description" TEXT,
    "IsActive" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "Order" (
    "OrderID" UUID NOT NULL PRIMARY KEY,
    "BuyerUserID" UUID NOT NULL,
    "BuyerApplicationID" UUID NOT NULL,
    "BuyerLocationID" UUID,
    "OrderStatusID" UUID NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "PlacedAt" TIMESTAMPTZ,
    "TotalAmount" NUMERIC(10,2),
    "Comment" TEXT
);

CREATE TABLE IF NOT EXISTS "OrderExportLog" (
    "OrderExportLogID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "Method" TEXT,
    "FileName" TEXT,
    "OrdersCount" INTEGER NOT NULL,
    "Status" TEXT NOT NULL,
    "Message" TEXT,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "OrderItem" (
    "OrderLineID" UUID NOT NULL PRIMARY KEY,
    "OrderID" UUID NOT NULL,
    "SupplierID" UUID NOT NULL,
    "SupplierItemID" UUID,
    "ProductID" UUID,
    "RegionID" UUID,
    "Qty" NUMERIC(10,2) NOT NULL,
    "UnitPrice" NUMERIC(10,2) NOT NULL,
    "PriceListID" UUID,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "SupplierPriceID" UUID,
    "ItemName" TEXT,
    "ItemCode" TEXT,
    "Barcode" TEXT
);

CREATE TABLE IF NOT EXISTS "OrderStatus" (
    "OrderStatusID" UUID NOT NULL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Description" TEXT,
    "IsActive" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "PriceFeed" (
    "PriceFeedID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "Name" TEXT NOT NULL,
    "SourceTypeID" UUID NOT NULL,
    "ScheduleCron" TEXT,
    "FilePattern" TEXT,
    "ApiPath" TEXT,
    "DefaultRegionID" UUID,
    "DefaultMarkupPct" NUMERIC(5,2),
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "PriceFeedRun" (
    "PriceFeedRunID" UUID NOT NULL PRIMARY KEY,
    "PriceFeedID" UUID NOT NULL,
    "StartedAt" TIMESTAMPTZ NOT NULL,
    "CompletedAt" TIMESTAMPTZ,
    "Status" TEXT NOT NULL,
    "RecordsProcessed" INTEGER,
    "RecordsFailed" INTEGER,
    "ErrorMessage" TEXT
);

CREATE TABLE IF NOT EXISTS "PriceList" (
    "PriceListID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "Name" TEXT NOT NULL,
    "Description" TEXT,
    "ImportPointID" UUID,
    "DefaultMarkupPct" NUMERIC(5,2),
    "ScheduleCron" TEXT,
    "LastUpdateAt" TIMESTAMPTZ,
    "NextUpdateAt" TIMESTAMPTZ,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL,
    "ValidDays" INTEGER
);

CREATE TABLE IF NOT EXISTS "PriceListRegion" (
    "PriceListRegionID" UUID NOT NULL PRIMARY KEY,
    "PriceListID" UUID NOT NULL,
    "RegionID" UUID NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "MarkupPct" NUMERIC(5,2),
    "BasePriceType" TEXT
);

CREATE TABLE IF NOT EXISTS "Product" (
    "ProductID" UUID NOT NULL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "INN" TEXT,
    "Form" TEXT,
    "Dosage" TEXT,
    "PackSize" TEXT,
    "Description" TEXT,
    "RxRequired" BOOLEAN,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "ProductBarcode" (
    "ProductBarcodeID" UUID NOT NULL PRIMARY KEY,
    "ProductID" UUID NOT NULL,
    "Barcode" TEXT NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "ProductSynonym" (
    "ProductSynonymID" UUID NOT NULL PRIMARY KEY,
    "ProductID" UUID NOT NULL,
    "Name" TEXT NOT NULL,
    "Source" TEXT,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "Region" (
    "RegionID" UUID NOT NULL PRIMARY KEY,
    "Code" TEXT NOT NULL,
    "Name" TEXT NOT NULL,
    "FederalDistrict" TEXT NOT NULL,
    "Capital" TEXT NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "SourceType" (
    "SourceTypeID" UUID NOT NULL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Description" TEXT,
    "IsActive" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS "Supplier" (
    "SupplierID" UUID NOT NULL PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Address" TEXT,
    "Contacts" TEXT,
    "INN" TEXT,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL,
    "ContractNumber" TEXT,
    "Login" TEXT,
    "Password" TEXT,
    "DeliveryAddress" TEXT
);

CREATE TABLE IF NOT EXISTS "SupplierBuyerConfig" (
    "ConfigID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "BuyerID" UUID NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "PriceColumn" TEXT,
    "MarkupPct" NUMERIC(5,2),
    "ClientCode" TEXT,
    "PaymentCode" TEXT,
    "DeliveryCode" TEXT,
    "ControlMinOrder" BOOLEAN NOT NULL,
    "MinOrderAmount" NUMERIC(12,2),
    "MinReorderAmount" NUMERIC(12,2),
    "UpdatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "SupplierExportConfig" (
    "SupplierExportConfigID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "Method" TEXT NOT NULL,
    "Format" TEXT NOT NULL,
    "FtpHost" TEXT,
    "FtpPort" INTEGER NOT NULL,
    "FtpUser" TEXT,
    "FtpPassword" TEXT,
    "FtpDir" TEXT,
    "EmailTo" TEXT,
    "SmtpHost" TEXT,
    "SmtpPort" INTEGER NOT NULL,
    "SmtpUser" TEXT,
    "SmtpPassword" TEXT,
    "SmtpFrom" TEXT,
    "IsActive" BOOLEAN NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "SupplierItem" (
    "SupplierItemID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "ExternalSKU" TEXT NOT NULL,
    "Name" TEXT NOT NULL,
    "Dosage" TEXT,
    "Form" TEXT,
    "PackSize" TEXT,
    "Barcode" TEXT,
    "ValidFrom" TIMESTAMPTZ NOT NULL,
    "ValidTo" TIMESTAMPTZ,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "SupplierItemMap" (
    "SupplierItemMapID" UUID NOT NULL PRIMARY KEY,
    "SupplierItemID" UUID NOT NULL,
    "ProductID" UUID NOT NULL,
    "MapStatusID" UUID NOT NULL,
    "IsManual" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "CreatedBy" TEXT
);

CREATE TABLE IF NOT EXISTS "SupplierItemMapping" (
    "MappingID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "ItemCode" TEXT NOT NULL,
    "GUID_ES" UUID NOT NULL,
    "MatchMethod" TEXT,
    "MatchConfidence" DOUBLE PRECISION,
    "UseCount" INTEGER NOT NULL,
    "LastUsedAt" TIMESTAMPTZ,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "SupplierMarkupPolicy" (
    "PolicyID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "RegionID" UUID,
    "ProductID" UUID,
    "MarkupPct" NUMERIC(5,2) NOT NULL,
    "RoundingStep" NUMERIC(10,2),
    "IsActive" BOOLEAN NOT NULL,
    "EffectiveFrom" TIMESTAMPTZ NOT NULL,
    "EffectiveTo" TIMESTAMPTZ,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "SupplierPrice" (
    "SupplierPriceID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "InvoiceImportID" UUID NOT NULL,
    "InvoiceDataID" UUID NOT NULL,
    "GUID_ES" UUID,
    "ItemCode" TEXT,
    "ItemName" TEXT,
    "SupplierItemName" TEXT,
    "Barcode" TEXT,
    "Price" NUMERIC(18,2) NOT NULL,
    "Quantity" NUMERIC(18,3),
    "InvoiceNumber" TEXT,
    "InvoiceDate" TIMESTAMPTZ,
    "BatchNumber" TEXT,
    "ExpiryDate" TIMESTAMPTZ,
    "MatchMethod" TEXT,
    "MatchConfidence" NUMERIC(5,2),
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL,
    "RegionID" UUID,
    "MarkupPct" NUMERIC(5,2),
    "FinalPrice" NUMERIC(31,9),
    "PriceListID" UUID,
    "Series" TEXT,
    "Manufacturer" TEXT,
    "Country" TEXT
);

CREATE TABLE IF NOT EXISTS "SupplierPriceHistory" (
    "PriceHistoryID" UUID NOT NULL PRIMARY KEY,
    "SupplierPriceID" UUID NOT NULL,
    "OldPrice" NUMERIC(18,2) NOT NULL,
    "NewPrice" NUMERIC(18,2) NOT NULL,
    "ChangedAt" TIMESTAMPTZ NOT NULL,
    "ChangedByInvoiceImportID" UUID,
    "Reason" TEXT,
    "OldItemName" TEXT,
    "NewItemName" TEXT,
    "OldItemCode" TEXT,
    "NewItemCode" TEXT,
    "OldBarcode" TEXT,
    "NewBarcode" TEXT,
    "OldQuantity" NUMERIC(18,3),
    "NewQuantity" NUMERIC(18,3),
    "OldBatchNumber" TEXT,
    "NewBatchNumber" TEXT,
    "OldExpiryDate" TIMESTAMPTZ,
    "NewExpiryDate" TIMESTAMPTZ,
    "OldInvoiceNumber" TEXT,
    "NewInvoiceNumber" TEXT,
    "OldInvoiceDate" TIMESTAMPTZ,
    "NewInvoiceDate" TIMESTAMPTZ,
    "ChangeType" TEXT
);

CREATE TABLE IF NOT EXISTS "SupplierPriceList" (
    "PriceListID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "PriceFeedRunID" UUID NOT NULL,
    "VersionLabel" TEXT,
    "ValidFrom" TIMESTAMPTZ NOT NULL,
    "ValidTo" TIMESTAMPTZ,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "SupplierRegion" (
    "SupplierRegionID" UUID NOT NULL PRIMARY KEY,
    "SupplierID" UUID NOT NULL,
    "RegionID" UUID NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);

-- UNIQUE для ON CONFLICT в API / sync
CREATE UNIQUE INDEX IF NOT EXISTS "UX_SupplierItemMapping_Supplier_ItemCode"
    ON "SupplierItemMapping" ("SupplierID", "ItemCode");

CREATE UNIQUE INDEX IF NOT EXISTS "UX_PriceListRegion_PriceList_Region"
    ON "PriceListRegion" ("PriceListID", "RegionID");

CREATE UNIQUE INDEX IF NOT EXISTS "UX_DBFFieldMapping_ImportPoint_Field"
    ON "DBFFieldMapping" ("ImportPointID", "DBFFieldName");

CREATE UNIQUE INDEX IF NOT EXISTS "UX_SupplierRegion_Supplier_Region"
    ON "SupplierRegion" ("SupplierID", "RegionID");

CREATE UNIQUE INDEX IF NOT EXISTS "UX_BuyerPriceList_Buyer_PriceList"
    ON "BuyerPriceList" ("BuyerID", "PriceListID");

-- Проверка
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
